apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: erfgoed-boeking-svc
  namespace: ext
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: registry.digitalocean.com/webwize/erfgoed-boeking-svc-prod:latest
          imagePullPolicy: Always
